# Generated by Django 5.2.5 on 2025-08-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('pendidikan', models.TextField()),
                ('pengalaman', models.TextField()),
                ('keterampilan', models.TextField()),
                ('sertifikasi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
